name: Build and Deploy to S3

on:
  push:
    branches:
      - main

env :
  CODE_APP_NAME : my-codedeploy-test
  CODE_GROUP_NAME : boot-group

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run : ./gradlew clean build --exclude-task test
      - name: Check build folder
        run: ls -l build/libs/
# WAR 파일을 ZIP 파일로 묶기
      - name: Package WAR into ZIP
        run: |
          mkdir -p package
          cp build/libs/*-plain.war package/ROOT.war
          cp appspec.yml package/appspec.yml
          zip -r spring-app.zip package/

      # S3 자격증명 설정
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_ACC_KEY }}
          aws-secret-access-key: ${{ secrets.S3_SEC_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      # ZIP 파일을 S3에 업로드
      - name: Upload to S3
        run: aws s3 cp spring-app.zip s3://${{ secrets.S3_BUCKET_NAME }}/spring-app.zip
      
      # CodeDeploy 실행 (EC2에 배포)
      - name: Deploy to EC2 using CodeDeploy
        run: aws deploy create-deployment
          --application-name "$CODE_APP_NAME"
          --deployment-group-name "$CODE_GROUP_NAME"
          --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=spring-app.zip,bundleType=zip
          --region ${{ secrets.S3_REGION }}